// Copyright KELDRAN. Native gameplay tags (Docs/00_ImplementationSpec.md §1).
#pragma once

#include "NativeGameplayTags.h"

// Races
KELDRANCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Race_Freeborn);
// Classes
KELDRANCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Class_Warden);
// Input ability slots
KELDRANCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Input_Ability_Slot1);
KELDRANCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Input_Ability_Slot2);
KELDRANCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Input_Ability_Slot3);
// States
KELDRANCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_State_Dead);
KELDRANCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_State_Stunned);
// Factions
KELDRANCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Faction_Covenant);
KELDRANCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Faction_FreePact);
KELDRANCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Faction_Hollow);
